name: Elixir CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_call:

env:
  MIX_ENV: "test"
  SECRET_KEY_BASE: "FH0XS5rdftWJzFtrO0vZthEP+BF/m/9lZYC6MAZa5nHjOLDdlP2g5U3hSJCBnD3B"
  LIVE_VIEW_SALT: "oh8aX0/4A6KqRcPHKAD8nisib4JkLQ+b"

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:10.4
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres 
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.19.0'
        otp-version: '28.0'

    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix deps.get

    - name: Compile
      run: mix compile --warnings-as-errors

    - name: Check format
      run: mix format --check-formatted

    - name: Run tests
      run: mix test
